### ISSUE TITLE
Conflict single letter option "-R"

### ISSUE THREAD

**Issue by miurahr** [astropy/pytest-remotedata#67]
pytest-remotedata defines single letter option "-R". Unfortunately pytest-leaks plugin also define it.
It is better to avoid define single letter option because of conflict.

Here is an example.
https://github.com/miurahr/aqtinstall/pull/634#issuecomment-1374884570

Could you remove a "-R" single letter option?

**Comment by bsipocz** [comment]
We're using the single letter option for quite some time in the astropy context, and I would rather like to keep having this option. 

But if possible to move it into the wrapper package of `pytest-astropy`, I would not be against removing it from `pytest-remotedata`.

**Comment by ddalcino** [comment]
> We're using the single letter option for quite some time in the astropy context, and I would rather like to keep having this option.

As far as I can tell, this is a new option as of the December 11, 2022 release v 0.4.0. Our CI builds have been broken since then, because of the conflict with pytest-leaks, which has used the -R option for several years. If this option remains, we will be forced to either stick to older versions of this project or change dependencies. We need both libraries. What do you recommend that we do?

> But if possible to move it into the wrapper package of `pytest-astropy`, I would not be against removing it from `pytest-remotedata`.

That sounds like a pretty good idea.

**Comment by miurahr** [comment]
I've also asked `pytest-leaks` project to ask removing `-R` option. There is no response.
https://github.com/abalkin/pytest-leaks/issues/41

**Comment by pllim** [comment]
You know, there is no "r" in "leaks"... 😹
